name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@2.3.19 #Github Action version
        with:
          cx_tenant: Assurant
          base_uri: https://us.ast.checkmarx.net 
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
